# Generated by Django 5.0 on 2024-01-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
