# Generated by Django 5.0 on 2024-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('partner_image', models.ImageField(default='', upload_to='uploads/partners/')),
                ('partner_blog', models.CharField(max_length=5000)),
                ('social_url', models.URLField(max_length=2856)),
                ('age', models.IntegerField(blank=True, default='', null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
