# Generated by Django 5.0.2 on 2024-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
