# Generated by Django 5.0.2 on 2024-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0009_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=250),
        ),
    ]
