# Generated by Django 5.0.2 on 2024-05-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0010_alter_partner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
