# Generated by Django 5.0.2 on 2024-05-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0013_alter_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
