# Generated by Django 5.0.6 on 2024-06-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0014_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
