# Generated by Django 5.0.6 on 2024-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('druu', '0015_delete_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
